### ISSUE TITLE
Problem running tartufo on my local macbook after the upgrade

### ISSUE THREAD

**Issue by akothari-godaddy** [godaddy/tartufo-action#6]
```
tartufo --config ./tartofu.toml scan-local-repo --branch dev .
Traceback (most recent call last):
 File "/usr/local/bin/tartufo", line 8, in <module>
  sys.exit(main())
 File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
  return self.main(*args, **kwargs)
 File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
  rv = self.invoke(ctx)
 File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
  return _process_result(sub_ctx.command.invoke(sub_ctx))
 File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
  return ctx.invoke(self.callback, **ctx.params)
 File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
  return __callback(*args, **kwargs)
 File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 38, in new_func
  return f(get_current_context().obj, *args, **kwargs)
 File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
  return f(get_current_context(), *args, **kwargs)
 File "/usr/local/lib/python3.9/site-packages/tartufo/commands/scan_local_repo.py", line 51, in main
  util.process_issues(repo_path, scanner, options)
 File "/usr/local/lib/python3.9/site-packages/tartufo/util.py", line 253, in process_issues
  echo_result(options, scan, repo_path, output_dir)
 File "/usr/local/lib/python3.9/site-packages/tartufo/util.py", line 104, in echo_result
  for issue in scanner.scan():
 File "/usr/local/lib/python3.9/site-packages/tartufo/scanner.py", line 578, in scan
  for issue in self.scan_entropy(chunk):
 File "/usr/local/lib/python3.9/site-packages/tartufo/scanner.py", line 601, in scan_entropy
  yield from self.evaluate_entropy_string(
 File "/usr/local/lib/python3.9/site-packages/tartufo/scanner.py", line 623, in evaluate_entropy_string
  if self.entropy_string_is_excluded(string, line, chunk.file_path):
 File "/usr/local/lib/python3.9/site-packages/tartufo/scanner.py", line 468, in entropy_string_is_excluded
  return bool(self.excluded_entropy) and any(
 File "/usr/local/lib/python3.9/site-packages/tartufo/scanner.py", line 286, in excluded_entropy
  self._excluded_entropy = config.compile_rules(patterns) if patterns else []
 File "/usr/local/lib/python3.9/site-packages/tartufo/config.py", line 287, in compile_rules
  match_type = MatchType(pattern.get("match-type", MatchType.Search.value))
AttributeError: 'String' object has no attribute 'get'
```

If I remove config, tartufo.toml isnt detected

[tool.tartufo]
repo-path = "."
json = false
regex = true
entropy = true
exclude-signatures = []
exclude-path-patterns = [
    { path-pattern = 'go.sum', reason = 'Module hashes' },
    { path-pattern = 'tartufo.toml', reason = 'This file' },
    { path-pattern = 'Dockerfile', reason = 'GITHUB_TOKEN url' },
    { path-pattern = 'Makefile', reason = 'GITHUB_TOKEN url' },
    { path-pattern = 'deployments/*', reason = 'This file' },
    { path-pattern = 'swagger-ui/*', reason = 'This file' },
    { path-pattern = 'config.*/*', reason = 'This file' }, 
    { path-pattern = ".github/workflows/build-deploy.yaml", reason = 'This file' }, 
    { path-pattern = ".github/workflows/create-runners.yaml", reason = 'This file' }, 
    { path-pattern = ".github/workflows/delete-runners.yaml", reason = 'This file' }, 
    { path-pattern = ".github/workflows/golang.yaml", reason = 'This file' }, 
]
exclude-entropy-patterns = [
  ".github/workflows/.*.yaml::^[a-zA-Z0-9]{40}$", # git SHAs in GH workflows
  ".github/actions/.*/action.yaml::^[a-zA-Z0-9]{40}$",
]

**Comment by akothari-godaddy** [comment]
See https://tartufo.readthedocs.io/en/stable/configuration.html#:~:text=Entropy%20Exclusion%20Patterns
the entropy exclusion patterns must be each a dict with various parameters, and not just a string.
